package org.firstinspires.ftc.teamcode.enums.drivestates;

public enum HighGoalTwoWobblesStack {
    WAIT_FOR_START,
    DRIVE_TO_SHOTS,
    FIRST_SHOTS,
    BACK_TO_STACK,
    INTAKE_STACK,
    BACK_FROM_STACK,
    SHOOT_HIGH,
    BACK_TO_STACK_AGAIN,
    INTAKE_STACK_AGAIN,
    BACK_FROM_STACK_AGAIN,
    SHOOT_HIGH_AGAIN,
    APPROACH_WOBBLE,
    PLACE_WOBBLE,
    BACK_FROM_WOBBLE,
    GO_TO_BACK_OF_FIELD,
    GO_TO_SECOND_WOBBLE,
    GRAB_SECOND_WOBBLE,
    BACK_FROM_WOBBLE_GRAB,
    APPROACH_SECOND_WOBBLE,
    PLACE_SECOND_WOBBLE,
    BACK_FROM_SECOND_WOBBLE,
    PARK
}